# Generated by Django 5.2.8 on 2025-12-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount_paid',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='title',
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(default=25164505, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
    ]
