# Generated by Django 6.0 on 2025-12-31 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_housingapplication_governorate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingapplication',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='applications/profiles/'),
        ),
        migrations.AlterField(
            model_name='housingapplication',
            name='university_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='applications/ids/'),
        ),
    ]
