# Generated by Django 5.2.8 on 2025-12-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='cost',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='studentservice',
            old_name='is_active',
            new_name='active',
        ),
        migrations.AddField(
            model_name='studentservice',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
