# Generated by Django 6.0 on 2025-12-07 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def convert_empty_phone_to_null(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    CustomUser.objects.filter(phone='').update(phone=None)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_age_customuser_governorate'),
        ('housing', '0003_alter_room_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_picture',
            new_name='profile_photo',
        ),
        # Step 1: Make phone nullable (without unique)
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        # Step 2: Convert empty strings to None
        migrations.RunPython(convert_empty_phone_to_null),
        # Step 3: Apply unique constraint
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='housing.room')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
