# Generated by Django 6.0 on 2025-12-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_email_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='governorate',
            field=models.CharField(blank=True, choices=[("Sana'a", 'صنعاء'), ('Al Jawf', 'الجوف'), ("Ma'rib", 'مارب'), ("Sa'ada", 'صعدة'), ('Amran', 'عمران'), ('Ibb', 'اب'), ('Dhamar', 'ذمار'), ('Al Bayda', 'البيضاء'), ('Shabwah', 'شبوة'), ('Al Hudaydah', 'الحديدة')], max_length=100),
        ),
    ]
