# Generated by Django 5.2.8 on 2025-12-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_governorate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='governorate',
            field=models.CharField(choices=[("Sana'a", 'صنعاء'), ('Al Jawf', 'الجوف'), ("Ma'rib", 'مارب'), ("Sa'ada", 'صعدة'), ('Amran', 'عمران'), ('Ibb', 'اب'), ('Dhamar', 'ذمار'), ('Al Bayda', 'البيضاء'), ('Shabwah', 'شبوة'), ('Al Hudaydah', 'الحديدة')], max_length=100),
        ),
    ]
