# Generated by Django 5.2.8 on 2025-12-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentApplication',
        ),
    ]
