# Generated by Django 6.0 on 2025-12-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_delete_studentapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='available', max_length=20),
        ),
    ]
